services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  app:
    image: order:latest
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - mongo
volumes:
  mongo-data:
