spring:
  application:
    name: order
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  data:
    mongodb:
      host: mongo
      port: 27017

management:
  endpoints:
    web:
      exposure:
        include: health,httpexchanges
  endpoint.health.show-details: always

logging:
  level:
    org.springframework.boot.actuate.trace.http: TRACE

cache.eviction.cron: 0 */30 * ? * *
      